### ISSUE TITLE
How to set 32 bit per sample?

### ISSUE THREAD

**Issue by constant-flow** [pschatzmann/arduino-snapclient#17]
Hi, the DAC I use (TAS5713) requires a high clock rate for the MCLK as i learned from the squeezelite project.

> The tas5713 typically has the mclk connected to the sclk. In this
> configuration, mclk must be a multiple of the sclk. The lowest workable
> multiple is 64x. To achieve this,  32 bits per channel on must be sent
> over I2S. Reconfigure the I2S for that here, and expand the I2S stream
> when it is sent

Doing this based of from the sample code provided here

```
auto cfg = out.defaultConfig();
...
cfg.bits_per_sample = 32;
```

Is not sufficient to convince the lib to start 32 bit sample stream, it always falls back to 16.
How to setup the stream properly with something like the expansion as mentioned above?

**Comment by pschatzmann** [comment]
https://github.com/pschatzmann/arduino-audio-tools/wiki/Converting-the-Data-Format
