### ISSUE TITLE
set -> addNotifyAudioChange

### ISSUE THREAD

**Issue by LuNiPriSe** [pschatzmann/arduino-snapclient#21]
Seems like you updated the AudioTools but not the snapcast client.

/Arduino/libraries/snapclient/src/api/SnapOutput.h:205:20: error: 'class audio_tools::EncodedAudioStream' has no member named 'setNotifyAudioChange'; did you mean 'addNotifyAudioChange'?
     decoder_stream.setNotifyAudioChange(*this);
                    ^~~~~~~~~~~~~~~~~~~~
                    addNotifyAudioChange

**Comment by pschatzmann** [comment]
Yes, indeed. The correction has been committed...
