### ISSUE TITLE
File #include "Concurrency/Concurrency.h" not found

### ISSUE THREAD

**Issue by jaapnoordzij** [pschatzmann/arduino-snapclient#32]
In file api/SnapProcessorRTOS.h the include #include "Concurrency/Concurrency.h"
cannot be found.

I have commented out the line and everything works fine.

Great library, thanks a lot
Jaap

**Comment by pschatzmann** [comment]
Thanks for letting me know: Concurrency.h has been moved to AudioLibs in the AudioTools.
I have committed the necesarry correction...
