### ISSUE TITLE
can't compile SnapClientI2S example with arduino-ide 2.3.3

### ISSUE THREAD

**Issue by auhgit** [pschatzmann/arduino-snapclient#37]
Hi, i try to compile your SnapClientI2S example and got  ...

my hardware is a LyraT-mini v1.2 , i'm using arduino-ide 2.3.3 fresh install

`In file included from /home/auh/Arduino/libraries/audio-tools/src/Concurrency/BufferRTOS.h:3,
                 from /home/auh/Arduino/libraries/audio-tools/src/AudioLibs/Concurrency.h:8,
                 from /home/auh/Arduino/libraries/audio-tools/src/AudioTools.h:68,
                 from /tmp/.arduinoIDE-unsaved2024829-2430826-a0svrf.flbq4/sketch_sep29b/sketch_sep29b.ino:1:
/home/auh/Arduino/libraries/audio-tools/src/AudioTools/Buffers.h: In instantiation of 'void audio_tools::NBuffer<T>::resize(int, int) [with T = unsigned char]':
/home/auh/Arduino/libraries/audio-tools/src/AudioTools/Buffers.h:701:16:   required from here
/home/auh/Arduino/libraries/audio-tools/src/AudioTools/Buffers.h:711:24: error: no match for 'operator[]' (operand types are 'audio_tools::QueueFromVector<audio_tools::BaseBuffer<unsigned char>*>' and 'int')
  711 |       available_buffers[j] = new SingleBuffer<T>(size);
      |       ~~~~~~~~~~~~~~~~~^
/home/auh/Arduino/libraries/audio-tools/src/AudioTools/Buffers.h:712:28: error: no match for 'operator[]' (operand types are 'audio_tools::QueueFromVector<audio_tools::BaseBuffer<unsigned char>*>' and 'int')
  712 |       if (available_buffers[j] == nullptr) {
      |           ~~~~~~~~~~~~~~~~~^

exit status 1

Compilation error: exit status 1`

**Comment by pschatzmann** [comment]
I think you picked up the audiotools in some inconsistent state.
Try again with the latest corrections and let me know if this did not help.
I could not reproduce this with my lastest commit....
